services:
  deploymate:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: deploymate-app

    ports:
      - "5000:5000"

    volumes:
      - /home/rubar/deploymate/reports:/app/reports

    restart: unless-stopped
