name: DeployMate CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Test Flask application
        run: |
          python -m py_compile app/app.py

  docker-build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t deploymate:latest \
            .

      - name: Verify Docker image
        run: |
          docker images deploymate
